.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GZCLIENT" "1" "March 2022" ""
.SH "NAME"
\fBgzclient\fR \- Gazebo GUI Client
.SH "SYNOPSIS"
\fBgzclient\fR \fIoptions\fR
.SH "DESCRIPTION"
Gazebo GUI client which allows visualization and user interaction\.
.SH "OPTIONS"
.TP
\-v, \-\-version
Output version information\.
.TP
\-\-verbose
Increase the messages written to the terminal\.
.TP
\-h, \-\-help
Produce this help message\.
.TP
\-\-gui\-client\-plugin arg
Load a GUI plugin\.
.TP
\-g, \-\-gui\-plugin arg
Load a System plugin (deprecated, backwards compatibility reasons)\.
.SH "AUTHOR"
Open Source Robotics Foundation
.SH "COPYRIGHT"
Copyright (C) 2012 Open Source Robotics Foundation
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\.
