.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GZPROP" "1" "March 2022" ""
.SH "NAME"
\fBgzprop\fR \- Package a model for thepropshop\.org
.SH "SYNOPSIS"
\fBgzprop\fR \fImodel_directory\fR
.SH "DESCRIPTION"
Package an existing model directory into a tarball suitable for upload to thepropshop\.org\. A working instance of Gazebo >= 3\.0 is required\.
.SH "OPTIONS"
.TP
\-h, \-\-help
Output this help message\.
.SH "SEE ALSO"
ThePropShop website: http://thepropshop\.org
.SH "AUTHOR"
Open Source Robotics Foundation
.SH "COPYRIGHT"
Copyright (C) 2012 Open Source Robotics Foundation
.P
Licensed under the Apache License, Version 2\.0 (the "License"); you may not use this file except in compliance with the License\.
